#! /usr/bin/env python
##!/usr/bin/python
# Python code
# 
#
#import support.twitter as twitter
import support.tweetstream as tweetstream
import re
import getpass
import base64
import subprocess
import os


user_n = "nokia"
words_n = "nokia"
sec_ = 5
settingsfile = "config.ini"
dctfile = "dictfile"
passwd = "passwd"
linkdict = {}

def dictreader(dctfile):
	dct = {}
	if os.path.isfile(dctfile):
		f = open(dctfile)
		for line in f.readlines():
			dct[line.strip("\n")] = "Done"
		f.close()
	return dct

def dictwriter(dctfile,dct):
	f = open(dctfile,"w")
	tup = [c+"\n" for c in dct.keys()]
	f.writelines(tup)
	f.close()





def runme(user_n,words_n,my_user_n,my_pass,linkdict):
	print user_n,words_n
	print my_user_n,"xxxxx"
	people = []
	#people = [17351972]
	#people = user_n
	people.append(user_n)
	with tweetstream.FilterStream(my_user_n, my_pass,follow=people) as stream:
		for tweet in stream:
			data = tweet["text"]
			#print "Your tweet" ,tweet["text"]
			found = re.findall(".*?("+words_n+").*",data,re.I)
			if len(found)!=0:
				links = re.findall(".*?(http:\/\/\S+).*?",data,re.I)
				if len(links)!=0:
					for link in links:
						if link not in linkdict:
							print link
							subprocess.call(("open",link))
							linkdict[link]="Done"

if __name__ == "__main__":

	if os.path.exists(settingsfile):
		fr = open(settingsfile)
		data = fr.read()
		ma = re.findall("My\s*User\s*Name\s*:\s*(\S*)",data,re.IGNORECASE)
		if ma != []:
			my_user_n = ma[0]
		ma = re.findall("User\s*Id\s*:\s*(\d*)",data,re.IGNORECASE)
		if ma != []:
			user_n = ma[0]
		ma = re.findall("Word\s*:\s*(\S+.*)",data,re.IGNORECASE)
		if ma != []:
			words_n = ma[0]
		fr.close()
		if os.path.isfile(passwd):
			fr = open(passwd)
			my_pass = fr.read()
			my_pass = base64.b64decode(my_pass)
			fr.close()
		else:
			my_pass = getpass.getpass()
			w_pass = base64.b64encode(my_pass)
			fr = open(passwd,"w")
			fr.write(w_pass)
			fr.close()


		runme(user_n,words_n,my_user_n,my_pass,linkdict)

	
